# 使用Logistic Regression做CTR预估

## 数据：Avazu公司提供的点击率预估，预测一个广告是否会被点击

	https://www.kaggle.com/c/avazu-ctr-prediction/data

## 数据文件
**train** - Training set. 10 days of click-through data, ordered chronologically. Non-clicks and clicks are subsampled according to different strategies. 

	https://www.kaggle.com/c/avazu-ctr-prediction/download/train.gz

**test** - Test set. 1 day of ads to for testing your model predictions. 

	https://www.kaggle.com/c/avazu-ctr-prediction/download/test.gz

**sampleSubmission.csv** - Sample submission file in the correct format, corresponds to the All-0.5 Benchmark. 

	https://www.kaggle.com/c/avazu-ctr-prediction/download/sampleSubmission.gz

### 原始数据集太大，选择训练集中前100,000 个样本，构成train_small.csv

## 数据字段
id: ad identifier
click: 0/1 for non-click/click
hour: format is YYMMDDHH, so 14091123 means 23:00 on Sept. 11, 2014 UTC.

C1 -- anonymized categorical variable, banner_pos, site_id, site_domain, site_category, app_id, app_domain, app_category, device_id, device_ip, device_model, device_type, device_conn_type, C14-C21 -- anonymized categorical variables

# Load Data

In [4]:
import pandas as pd


# Initial setup
train_filename = "train_small.csv"
test_filename = "test.csv"
submission_filename = "submit.csv"

training_set = pd.read_csv(train_filename)

# Explore Data

In [5]:
training_set.head(10)

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157
5,1.000072e+19,0,14102100,1005,0,d6137915,bb1ef334,f028772b,ecad2386,7801e8d9,...,1,0,16920,320,50,1899,0,431,100077,117
6,1.000072e+19,0,14102100,1005,0,8fda644b,25d4cfcd,f028772b,ecad2386,7801e8d9,...,1,0,20362,320,50,2333,0,39,-1,157
7,1.000092e+19,0,14102100,1005,1,e151e245,7e091613,f028772b,ecad2386,7801e8d9,...,1,0,20632,320,50,2374,3,39,-1,23
8,1.000095e+19,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15707,320,50,1722,0,35,-1,79
9,1.000126e+19,0,14102100,1002,0,84c7ba46,c4e18dd6,50e219e0,ecad2386,7801e8d9,...,0,0,21689,320,50,2496,3,167,100191,23

In [6]:
training_set.describe()

,id,click,hour,C1,banner_pos,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
count,9.999900e+04,99999.000000,99999.0,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000
mean,9.500834e+18,0.174902,14102100.0,1005.034440,0.198302,1.055741,0.199272,17682.106071,318.333943,56.818988,1964.029090,0.789328,131.735447,37874.606366,88.555386
std,5.669435e+18,0.379885,0.0,1.088705,0.402641,0.583986,0.635271,3237.726956,11.931998,36.924283,394.961129,1.223747,244.077816,48546.369299,45.482979
min,3.237563e+13,0.000000,14102100.0,1001.000000,0.000000,0.000000,0.000000,375.000000,120.000000,20.000000,112.000000,0.000000,33.000000,-1.000000,13.000000
25%,4.183306e+18,0.000000,14102100.0,1005.000000,0.000000,1.000000,0.000000,15704.000000,320.000000,50.000000,1722.000000,0.000000,35.000000,-1.000000,61.000000
50%,1.074496e+19,0.000000,14102100.0,1005.000000,0.000000,1.000000,0.000000,17654.000000,320.000000,50.000000,1993.000000,0.000000,35.000000,-1.000000,79.000000
75%,1.457544e+19,0.000000,14102100.0,1005.000000,0.000000,1.000000,0.000000,20362.000000,320.000000,50.000000,2306.000000,2.000000,39.000000,100083.000000,156.000000
max,1.844670e+19,1.000000,14102100.0,1010.000000,5.000000,5.000000,5.000000,21705.000000,728.000000,480.000000,2497.000000,3.000000,1835.000000,100248.000000,157.000000

In [7]:
training_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 24 columns):
id                  99999 non-null float64
click               99999 non-null int64
hour                99999 non-null int64
C1                  99999 non-null int64
banner_pos          99999 non-null int64
site_id             99999 non-null object
site_domain         99999 non-null object
site_category       99999 non-null object
app_id              99999 non-null object
app_domain          99999 non-null object
app_category        99999 non-null object
device_id           99999 non-null object
device_ip           99999 non-null object
device_model        99999 non-null object
device_type         99999 non-null int64
device_conn_type    99999 non-null int64
C14                 99999 non-null int64
C15                 99999 non-null int64
C16                 99999 non-null int64
C17                 99999 non-null int64
C18                 99999 non-null int64
C19                 99999 non-null int64
C20                 99999 non-null int64
C21                 99999 non-null int64
dtypes: float64(1), int64(14), object(9)
memory usage: 18.3+ MB

In [8]:
training_set['C1'].unique()

array([1005, 1002, 1010, 1001, 1007, 1008])

In [11]:
var = ['C1','site_category','app_category','device_model','device_type','device_conn_type', 'C15','C16','C18','C19','C20']
for v in var:
    print '\n%s属性的不同取值和出现的次数\n'%v
    print training_set[v].value_counts()

C1属性的不同取值和出现的次数

1005    92454
1002     4211
1010     3191
1007      104
1001       29
1008       10
Name: C1, dtype: int64

site_category属性的不同取值和出现的次数

28905ebd    37696
50e219e0    25398
f028772b    19760
3e814130    12480
76b2941d     1843
335d28a8     1329
0569f928      675
72722551      314
f66779e6      279
75fa27f6      146
c0dd3be3       55
bcf865d9       13
a818d37a        7
42a36e14        2
110ab22d        1
e787de0e        1
Name: site_category, dtype: int64

app_category属性的不同取值和出现的次数

07d7df22    78827
0f2161f8    14971
f95efa07     2895
8ded1f7a     1347
cef3e649     1309
75d80bbe      171
4ce2e9fc      130
d1327cf5      129
09481d60       50
fc6fa53d       41
dc97ec06       40
a3c42688       32
0f9a328c       18
879c24eb       16
a86a3e89        8
7113d72a        7
a7fd01ec        4
8df2e842        2
4681bb9d        2
Name: app_category, dtype: int64

device_model属性的不同取值和出现的次数

8a4875bd    6886
d787e91b    5438
1f0bc64f    3769
4ea23a13    2301
711ee120    2108
c6263d8a    1701
a0f5f879    1626
ecb851b2    1588
3bd9e8e7    1573
f07e20f8    1497
36d749e5    1379
5096d134    1312
84ebbcd4    1291
779d90c2    1265
7abbbd5c    1195
24f6b932    1139
76dc4769    1137
900981af    1108
99e427c9     985
5db079b5     894
1ccc7835     829
6332421a     805
a5bce124     804
2203a096     772
0eb711ec     770
cf19f7f7     763
aad45b01     740
be74e6fe     737
158e4944     737
2ea4f8ba     661
            ...
239a8512       1
559c735b       1
5f75723b       1
aa03c32c       1
7a63d37c       1
eb3f4b48       1
c7246000       1
4082ae6a       1
cb02923d       1
e809467d       1
a10bbbc2       1
ec7a8616       1
c0120dcf       1
2055d165       1
32d0ea5e       1
5d300f40       1
5a5ac175       1
a525314e       1
1a9c364b       1
fd414d37       1
bb68f9d1       1
baa3d4c5       1
3b5f505c       1
be1b1994       1
8741c65a       1
3f03eb80       1
e4169825       1
3b6cd544       1
80c2a034       1
3ef14722       1
Name: device_model, Length: 2473, dtype: int64

device_type属性的不同取值和出现的次数

1    92597
0     4211
4     2979
5      212
Name: device_type, dtype: int64

device_conn_type属性的不同取值和出现的次数

0    90707
2     8097
3     1121
5       74
Name: device_conn_type, dtype: int64

C15属性的不同取值和出现的次数

320    95132
300     3935
216      912
728       18
120        2
Name: C15, dtype: int64

C16属性的不同取值和出现的次数

50     95620
250     3427
36       912
480       20
90        18
20         2
Name: C16, dtype: int64

C18属性的不同取值和出现的次数

0    69496
3    18133
2    12163
1      207
Name: C18, dtype: int64

C19属性的不同取值和出现的次数

35      55796
39      21930
297      4034
687      2683
1063     2393
163      2305
167      2111
303      1589
431      1147
427      1082
171       878
551       655
47        465
161       419
813       403
681       367
1319      290
175       280
1711      212
291       171
43        170
943       118
1835       98
1315       74
169        70
41         67
1451       55
801        35
683        34
1327       15
559        11
679        10
673        10
423         7
1071        6
33          5
425         4
Name: C19, dtype: int64

C20属性的不同取值和出现的次数

-1         62161
 100084    11567
 100111     3997
 100083     3746
 100077     1511
 100081     1374
 100075     1320
 100148     1121
 100000      970
 100034      929
 100228      827
 100074      772
 100079      536
 100105      502
 100210      440
 100130      434
 100020      418
 100217      375
 100028      367
 100050      325
 100131      308
 100046      293
 100156      268
 100128      267
 100191      240
 100119      234
 100233      220
 100193      218
 100215      211
 100188      194
           ...
 100004        8
 100055        7
 100097        7
 100029        6
 100124        6
 100061        6
 100091        5
 100056        4
 100040        4
 100099        3
 100123        3
 100195        3
 100112        3
 100051        3
 100177        2
 100152        2
 100138        2
 100043        2
 100133        2
 100143        2
 100016        2
 100185        2
 100058        2
 100213        1
 100229        1
 100064        1
 100093        1
 100071        1
 100090        1
 100024        1
Name: C20, Length: 137, dtype: int64

In [4]:
# id: ad identifier
# click: 0/1 for non-click/click
# hour: format is YYMMDDHH, so 14091123 means 23:00 on Sept. 11, 2014 UTC.
# C1 -- anonymized categorical variable
# banner_pos
# site_id
# site_domain
# site_category
# app_id
# app_domain
# app_category
# device_id
# device_ip
# device_model
# device_type
# device_conn_type
# C14-C21 -- anonymized categorical variables
from sklearn.externals import joblib
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

from utils import load_df

/Library/Python/2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [5]:
# 结果衡量
def print_metrics(true_values, predicted_values):
    print "Accuracy: ", metrics.accuracy_score(true_values, predicted_values)
    print "AUC: ", metrics.roc_auc_score(true_values, predicted_values)
    print "Confusion Matrix: ", + metrics.confusion_matrix(true_values, predicted_values)
    print metrics.classification_report(true_values, predicted_values)

# 拟合分类器
def classify(classifier_class, train_input, train_targets):
    classifier_object = classifier_class()
    classifier_object.fit(train_input, train_targets)
    return classifier_object

# 模型存储
def save_model(clf):
    joblib.dump(clf, 'classifier.pkl')

In [6]:
#drop了9个类别型的特征
train_data = load_df('train_small.csv').values

/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py:2825: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [8]:
train_data[:,:]

array([[       0, 14102100,     1005, ...,       35,       -1,       79],
       [       0, 14102100,     1005, ...,       35,   100084,       79],
       [       0, 14102100,     1005, ...,       35,   100084,       79],
       ...,
       [       0, 14102100,     1005, ...,       35,       -1,       79],
       [       1, 14102100,     1005, ...,       35,       -1,       79],
       [       0, 14102100,     1005, ...,       35,       -1,       79]])

In [9]:
# 训练和存储模型
X_train, X_test, y_train, y_test = train_test_split(train_data[0::, 1::], train_data[0::, 0],
                                                    test_size=0.3, random_state=0)

classifier = classify(LogisticRegression, X_train, y_train)
predictions = classifier.predict(X_test)
print_metrics(y_test, predictions)
save_model(classifier)

Accuracy:  0.8233
AUC:  0.5
Confusion Matrix:  [[24699     0]
 [ 5301     0]]
             precision    recall  f1-score   support

          0       0.82      1.00      0.90     24699
          1       0.00      0.00      0.00      5301

avg / total       0.68      0.82      0.74     30000

/usr/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
/Library/Python/2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

AUC为0.5，模型性能并不好，数据采样是一个原因，特征工程和模型简单是另一个原因（被点击的样本都预测错了:(）

In [12]:
# 按照指定的格式生成结果
def create_submission(ids, predictions, filename='submission.csv'):
    submissions = np.concatenate((ids.reshape(len(ids), 1), predictions.reshape(len(predictions), 1)), axis=1)
    df = DataFrame(submissions)
    df.to_csv(filename, header=['id', 'click'], index=False)

In [17]:
import numpy as np
from pandas import DataFrame

classifier = joblib.load('classifier.pkl')
test_data_df = load_df('test.csv', training=False)
ids = test_data_df.values[0:, 0]
predictions = classifier.predict(test_data_df.values[0:, 1:])
create_submission(ids, predictions)

## 样本数目太多，也可以采用SGDClassifier